### ISSUE TITLE
Roughness and metallic don't update in the viewport

### ISSUE THREAD

**Issue by wo262** [kmkolasinski/AwesomeBump#121]
![sin titulo](https://user-images.githubusercontent.com/29487655/27235238-436be560-52c0-11e7-8451-de9064808f82.png)

Happens on both GL330 and regular. 

Windows 10 64, intel i5 6400 intel HD 530

**Comment by jackjameshoward** [comment]
The same thing has happened to a few people now. I believe it is something to do with AB not being compatible with Windows 10 because of the Qt libraries.
@kmkolasinski has suggested to a few people to compile AB from source code but I didn't know how.
If somebody could try it for me that would be great.

**Comment by kmkolasinski** [comment]
Definitely it would be nice to see how other people are compiling AB on Win10, but sill no feedback from anyone... I'm linux guy and I have access to win7 for now. 
I just made a stable "Release" with code which should compile. Master is broken....

**Comment by kmkolasinski** [comment]
I believe this has been resolved in the newer versions.
