### ISSUE TITLE
Improve implementation of constructors

### ISSUE THREAD

**Issue by elfring** [kmkolasinski/AwesomeBump#34]
I have noticed that a couple of assignments are used in the constructor bodies.

Examples:
* [AwesomeCamera](https://github.com/kmkolasinski/AwesomeBump/blob/a15b4115e5548361be3f1e5be85267e8575bef28/Sources/camera.cpp#L5 "Camera constructor")
* [GLImage](https://github.com/kmkolasinski/AwesomeBump/blob/ccbb3324248f6e01489126349c3f7b4fecd9d3f2/Sources/glimageeditor.cpp#L44 "Image constructor")
* [MainWindow](https://github.com/kmkolasinski/AwesomeBump/blob/ccbb3324248f6e01489126349c3f7b4fecd9d3f2/Sources/mainwindow.cpp#L5 "Window constructor")

The recommended way for performing efficient construction is to use the initialisation list.
* [C++ FAQ](https://isocpp.org/wiki/faq/ctors#init-lists "Frequently asked questions and corresponding answers")
* [Article by Alex Allain](http://cprogramming.com/tutorial/initialization-lists-c++.html "Understanding Initialization Lists in C++")
* [Description by Danny Kalev](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=15&rl=1 "C++ Reference Guide - Constructors")

**Comment by kmkolasinski** [comment]
Hi, I know initialisation list, but how actually it will improve AB functionality? (I will read references in a free time)

**Comment by elfring** [comment]
I would appreciate another constructive comment after your question in April.

**Comment by kmkolasinski** [comment]
I have not read those links, because you didn't convince me why I should improve those constructors and as a pragmatic person, I don't want to spent on something which works.

**Comment by elfring** [comment]
Can information from the available literature be convincing enough?

**Comment by kmkolasinski** [comment]
Yes of course it can, but collaboration (in my opinion) is more about sharing experience between people, not just saying: "you are wrong, read this, this and that, and you will know why".  So mentioning why or how it could be useful for AwesomeBump would be a good motivation for me to read  literature provided by you. Otherwise, your first comment is just a bunch of links to articles which I don't want to read, because it takes time and I have more interesting things to do, since I have no profits from AB.
One doesn't have to be a "programmer" to be able to write programs, and I'm such a person.

**Comment by elfring** [comment]
Does an information source like the [C++ FAQ](https://isocpp.org/wiki/faq/ctors#init-lists "Frequently asked questions and corresponding answers") matter for you?

**Comment by kmkolasinski** [comment]
Correct me:
Its written:
Conclusion: All other things being equal, your code will run faster if you use initialization lists rather than assignment.
So it seems to be only the matter of speed?

**Comment by elfring** [comment]
* Is the aspect "speed" one of the major concerns for a programming language like "C++"?
* Do you care for exception safety?

**Comment by kmkolasinski** [comment]
Ad 1. As always for such generalized questions: it depends. Here it will not affect the speed, so it is not a concern for me.
Ad 2. As before, but now personal question, answer: it depends, sometimes I care sometimes not. I mostly program in Fortran, which does not know the exception idea.

Do you understand "pragmatic" word? Because it seems for me, you don't.

**Comment by elfring** [comment]
The involved maintainers can be so "pragmatic" of course to stay with the design decision that this software will not be made a bit more efficient at suggested source code places.

**Comment by kmkolasinski** [comment]
If you want you may help and contribute to this project. I don't see a problem if someone makes the parts of the code prettier and send me corrections by pull-requests.
