### ISSUE TITLE
About Normal Map enhancements

### ISSUE THREAD

**Issue by makklaski** [kmkolasinski/AwesomeBump#7]
Normal tab like other tabs has lots of sliders to 'enhance' the normal map.
But does it really makes sense to use them?
These sliders do not change the height map.
And a normal by definition is vector perpendicular to the surface.
It would be more logical to enhance height map and auto-generate normal map using texture's width, height and depth (in pixels or meters or anything else).
At the moment I don't know how to make a normal map which will match the height map with some specific depth. If my height texture is 2m by 2m by 10cm there can only be one possible normal map, by definition.
At the moment I can only use some magic numbers and hope for the best.

**Comment by kmkolasinski** [comment]
Hi, 
The AB pipeline is following:
1) take the input image 
2) convert it to normal map,
3) then convert it to heightmap,
so the height is the last texture which is generated from normal image (not in opposite way), and the normal texture parameters (during conversion) can be modify only in "basemap to others" section. 

But, you can always modify height after conversion, then convert it to normal texture.
I will keep the 'enhance' sliders because  they have different impact on normal image than the same sliders in height tab on height image. Maybe it is the same but the result will be different.
 
Secondly, I slowly working on new functionalities in AB v2.0 i.e. I am going to add height leveling sliders which will restrict the minimum and maximum values of height to some range. This featue will appear in next AB version. 
Regards,
KK

**Comment by makklaski** [comment]
Hello!
OK. I just want to know the thickness of generated height map. What is the distance between black and white colors?
For example, if all vectors in normal map have the same 45 degrees angle to the surface then the thickness of generated height map should match its width and height with linear gradient going from black to white.
Doesn't matter what is generated first, normal map or height map. They represent the same surface and by changing one of them the other should be changed accordingly, based on provided thickness value.
At the moment there is a Depth scale slider in Settings tab. If we are increasing the effect of displacement map then the steepness of normal map should also increase.
Otherwise normal map is not really normal map but just some fun bumpy effect not related to height in any way.

**Comment by kmkolasinski** [comment]
So, the height image is always normalized from 0 to 1. 
In order to get the same surface in height map and normal map you can follow this steps:
1) set the all sliders in normal tab to 0
2) then go to the height image an choose - height to normal convertion tool.
3) convert image,
4) then normal texture (in normal tab) should be exactly the same as normal texture visible in height tab with preview check box enabled.
Now both images (height,normal) should represent the same surface. That was your question?

I left the possiblity to change many things, in order to provide maximum flexibility for users. 

The depth slider change only the visual effect, it does not affect any textures. For example if you set depth to 0, you will have the case of standard bump mapping.

**Comment by kmkolasinski** [comment]
Ok, I think I understand what is your problem. There is no 'physical' parameter in AB which allow you to choose height of the texture (min, max values) then generate proper normal map, but there is a phenomenological parameter which is called 'Normal step' which is analogical to what you said. 

I will change it definitely, because you are again right and there must be a parameter which will allow the user to change the depth of the height image. Acctually, it will do exactly what 'Normal step' slider, but it will be more intuitive. For example 0 will mean completely flat surface and 1 will mean that maximum height is 1 meter.  
Thank you for feedback.
Best,
KK

**Comment by makklaski** [comment]
Thank you!
The width and height of a texture, in meters, should also be specified somewhere.
Or the thickness can be expressed in pixels.
For example: this texture is 200 by 100 pixels, and the thickness is 50 pixels. (distance between black and white colors of heightmap)
Or: this texture is 2 by 2 meters and the thickness is 1 meter.

**Comment by kmkolasinski** [comment]
I don't think this is necessary as well as you know the dimension of the image you can assume that one pixel is a unit of length (for example 1pixel = 1meter), thus there will be needed the only one parameter to describe  the surface-- height (expressed in pixels/meters).  If you will have texture of terrain you will just need to find proper scale factor which will allow you tranfsorm your image from e.g. 5km x 5km to 1024m x 1024m, which is easy to do.
