### ISSUE TITLE
Textures appear overly dark in AwesomeBump

### ISSUE THREAD

**Issue by Calinou** [kmkolasinski/AwesomeBump#85]
Is it just me, or textures appear overly dark in AwesomeBump compared to what one would see in a typical game engine? I often see myself bumping the Diffuse value to 2.0 so that the texture matches real-world scenarios more. Maybe the "fake contrast" applied to the 3D view is too intense?

**Comment by kmkolasinski** [comment]
Hey, it is possible that 3D view is cheating a bit. Currently, I'm quite busy but current version contains possibility to write your own fragment shader for 3D view, such that you can customize the view for your needs (engine). But for example saving and loading settings does not work yet, since we are changing GUI.

**Comment by kmkolasinski** [comment]
I meant that new version has something like that:
![img](https://github.com/kmkolasinski/AwesomeBump/blob/master/Wiki/Tests/guiProp2.png)

**Comment by kmkolasinski** [comment]
Hi, I'm closing this issue since the 3D setting are now available in prepared version 5.0
